Remove display command flag, handle flags better

diff --git a/pblocks b/pblocks
--- a/pblocks
+++ b/pblocks
@@ -5,33 +5,42 @@
 # written by Zubarev Grigoriy <thirtysix@thirtysix.pw> in 2023
 # licensed under the terms of GPLv3+
 
-
 die() {
 	printf "[1;31merror:[0m %s\\n" "$1" >&2
 	exit 1
 }
 
-config="${XDG_CONFIG_HOME:-$HOME/.config}/pblocks/pblocksrc"
-delim=" "
-displaycmd="xsetroot -name \\\"%bar%\\\""
-
-while getopts ":vhc:d:D:s" OPT; do case "$OPT" in
+while getopts ":vhc:d:s" OPT; do case "$OPT" in
 	v) printf "pblocks-VERSION\\n"; exit 0 ;;
-	h) { man pblocks && exit 0 ;} || die "could not open man page" ;;
-	c) config="$OPTARG" ;;
-	d) delim="$OPTARG" ;;
-	D) displaycmd="$OPTARG" ;;
-	s) displaycmd="printf \\\"%s\\n\\\" \\\"%bar%\\\"" ;;
+	h) man pblocks 2>/dev/null || die "could not open man page: 'pblocks'"; exit 0 ;;
+	c) [ -n "$config" ] && die "'-$OPT' does not support being passed multiple times"
+		config="$OPTARG" ;;
+	d) [ -n "$delim" ] && die "'-$OPT' does not support being passed multiple times"
+		delim="$OPTARG" ;;
+	s) [ -n "$displaycmd" ] && die "'-$OPT' does not support being passed multiple times"
+		displaycmd="printf \"%s\\n\"" ;;
+	:) die "'-$OPTARG' requires argument" ;;
 	\?) die "invalid option: '$OPTARG'" ;;
 esac done
 
-[ ! -f "$config" ] && die "config not found: '$config'"
+config="${config:-${XDG_CONFIG_HOME:-$HOME/.config}/pblocks/pblocksrc}"
+delim="${delim:- | }"
+if [ -z "$displaycmd" ]; then
+	if command -v xsetroot >/dev/null; then
+		displaycmd="xsetroot -name"
+	elif command -v xprop >/dev/null; then
+		displaycmd="xprop -root -set WM_NAME"
+	else
+		die "pblocks requires \`xsetroot\` or \`xprop\` to set dwm bar"
+	fi
+fi
 
-displaycmd="$(echo "$displaycmd" | sed 's/%bar%/${bar}/g')"
-display() { eval "eval \"$displaycmd\"" ;}
+[ ! -f "$config" ] && die "no such config file: '$config'"
+
+display() { eval "$displaycmd \"$bar\"" ;}
 
 temp="$(mktemp "${TMPDIR:-/tmp}/pblocks.XXX")"
-trap 'rm -f "$temp"; exit 0' HUP INT QUIT TERM PWR EXIT
+trap 'rm -f "$temp"; exit 0' HUP QUIT TERM PWR EXIT
 sed -e '/^\s*#/d' -e '/^\s*$/d' < "$config" > "$temp"
 
 bar=""
@@ -56,4 +65,4 @@ while :; do
 		done < "$temp"
 		sec=$((sec + 1))
 	}
-	done
+done
